version: '3.1'

services:

  ##################
  # Node Container
  ##################
  server:
    image: demonicmushy/chatbotplatform:server
    build:
      context: ../backend
    environment:
      - MICL_ENDPOINT=http://13.76.152.232:8081
      - FLASK_ENDPOINT=http://api:5000
      - SPEECH_API=ws://40.90.170.182:8001/client/ws/speech
      - SPEECH_HTTP_API=http://40.90.170.182:8001/client/dynamic/recognize
      - DIALOGFLOW_KEYFILENAME_COVID19=/run/secrets/dialog_covid19
      - DIALOGFLOW_KEYFILENAME_BABYBONUS=/run/secrets/dialog_babybonus
      - RAJAT_ENDPOINT_BABYBONUS=http://13.76.152.232:1995
      - RAJAT_ENDPOINT_COVID19=http://13.76.152.232:2995
      - AISG_TOKEN=/run/secrets/aisg_token
    ports:
      - '3001:3001'
    deploy:
      replicas: 1
    secrets:
      - dialog_babybonus
      - dialog_covid19
      - aisg_token

#    volumes:
#      - ../online_asr_backend/routes:/srv/app/server/routes
#    command: npm run dev

  ##################
  # Flask Container
  ##################
  api:
    image: demonicmushy/chatbotplatform:api
    build: ../comparison
    environment:
      - PORT=5000
    deploy:
      replicas: 1

   # volumes:
   #   - ../production:/api
   # command: python flaskApp.py
   # environment:
   #   - FLASK_ENV=development
   #   - FLASK_APP=flaskApp.py
   #   - FLASK_DEBUG=1

  ##################
  # Client Container
  ##################
  client:
    image: demonicmushy/chatbotplatform:client
    build:
      context: ../frontend
      args:
        # need to specify here because it will be complied into image
        - REACT_APP_API=https://chatbot.speechlab.sg:3001
    ports:
      - '3000:80'
    deploy:
      replicas: 1

#    volumes:
#      - ../dialogflowapp/src:/srv/app/client/src
#      - ../dialogflowapp/public:/srv/app/client/public
#    command: npm run start

secrets:
  dialog_babybonus:
    external: true
  dialog_covid19:
    external: true
  aisg_token:
    external: true
