version: '3'

services:

  ##################
  # Node Container
  ##################
  server:
    image: demonicmushy/chatbotplatform:server
    environment:
        - MICL_ENDPOINT=${MICL_ENDPOINT}
        - FLASK_ENDPOINT=${FLASK_ENDPOINT}
        - AISG_TOKEN=${AISG_TOKEN}
        - SPEECH_API=${SPEECH_API}
        - SPEECH_HTTP_API=${SPEECH_HTTP_API}
        - DIALOGFLOW_PROJECT_ID_COVID19=${DIALOGFLOW_PROJECT_ID_COVID19}
        - DIALOGFLOW_PROJECT_ID_BABYBONUS=${DIALOGFLOW_PROJECT_ID_BABYBONUS}
        - DIALOGFLOW_KEYFILENAME_COVID19=${DIALOGFLOW_KEYFILENAME_COVID19}
        - DIALOGFLOW_KEYFILENAME_BABYBONUS=${DIALOGFLOW_KEYFILENAME_BABYBONUS}
        - RAJAT_ENDPOINT_BABYBONUS=${RAJAT_ENDPOINT_BABYBONUS}
        - RAJAT_ENDPOINT_COVID19=${RAJAT_ENDPOINT_COVID19}
    #build:
    #  context: ../backend
    #  args:
    #    - KEY=${KEY}
    #    - PROJECTID=${PROJECTID}
    ports:
      - ${APP_SERVER_PORT_FOR_HTTPS}:${APP_SERVER_PORT}

  ##################
  # Flask Container
  ##################
  api:
    image: demonicmushy/chatbotplatform:api
    environment:
      - ${FLASK_SERVER_PORT}:${CONTAINER_PORT}
      - PORT=${CONTAINER_PORT}
    #build: ../comparison
    #ports:
    #  - ${FLASK_SERVER_PORT}:${CONTAINER_PORT}
    #environment:
    #  PORT: ${CONTAINER_PORT}

  ##################
  # Client Container
  ##################
  client:
    image: demonicmushy/chatbotplatform:client
    environment:
        - REACT_APP_API=${API_ENDPOINT}
    #build:
    #  context: ../frontend
    ports:
      - ${REACT_APP_PORT_FOR_HTTPS}:${NGINX_PORT}

  ####################
  # Rajat Model Covid19
  #####################
  rajat:
    image: demonicmushy/chatbotplatform:rajatcovid19
